export const btn = { textTransform: 'none', fontSize: '14px', fontFamily: 'Poppins', color: '#375EC0', border: '2px solid #375EC0' }
export const ptag = { fontSize: '13px', fontFamily: 'Poppins', color: '#6A707F', margin: '0', padding: '0' }
export const df_jc_ac = { display: 'flex', justifyContent: 'center', alignItems: 'center' }
export const df_jfe_ac = { display: 'flex', justifyContent: 'flex-end', alignItems: 'center', backgroundColor: '#161616'}
export const df_jfs_ac = { display: 'flex', justifyContent: 'flex-start', alignItems: 'center', color: '#fff' }
export const df_jfs_ac_fdc = { display: 'flex', justifyContent: 'center', alignItems: 'flex-start', flexDirection: 'column' }
export const textField = { width: '100%', marginBottom: '2%', backgroundColor: 'transparent', boxShadow: '0px 1px 26px rgba(94, 99, 116, 0.05)' }
export const bold_name = { fontFamily: 'Poppins', fontWeight: 'bold', color: '#fff' }
export const btn_connect = { textTransform: 'none', fontSize: '14px', borderRadius: '50px', fontFamily: 'Poppins', color: '#375EC0', border: '2px solid #375EC0', width: '100%', '&:hover': { backgroundColor: '#375EC0', color: 'white' } }
export const circularprog = { backgroundColor: '#375EC0', color: 'white', borderRadius: '50%', padding: '5px' }
export const link = { color: '#375EC0', textDecoration: 'underline', cursor: 'pointer' }